apiVersion: v1
kind: Service
metadata:
  name: dsp-redis-service
  labels:
    name: dsp-redis-service
spec:
  selector:
    name: dsp-redis
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379