apiVersion: v1
kind: Service
metadata:
  name: dsp-service
  labels:
    name: dsp-service
spec:
  selector:
    name: dsp
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 3000